version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule: 
      interval: "cron"
      cronjob: "23 14 1 * *"

  - package-ecosystem: "gradle"
    schedule: 
      interval: "cron"
      cronjob: "24 14 1 * *"
  
