name: Main

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v5
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Assemble Debug"
        run: ./gradlew :app:assembleDebug
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk